spring:
  profiles:
    active: heroku
  application:
    name: 'inventario-api'

keycloak:
  realm: catchup-realm
  auth-server-url: http://localhost:8081/auth
  ssl-required: external
  resource: maestro-client
  credentials:
    secret: 2d462b07-b424-49f1-bef6-db8480adb85e
  use-resource-role-mappings: true
  bearer-only: true

app:
  keycloak:
    serverUrl: http://localhost:8081/auth
    realm: catchup-realm
    clientId: maestro-client
    secret: 2d462b07-b424-49f1-bef6-db8480adb85e
  config:
    inventory:
      default-id: ${APP_CONFIG_INVENTORY_DEFAULT_ID:ZXC8GH}
    retry:
      max-attempts: ${APP_CONFIG_RETRY_MAX_ATTEMPTS:3}
      backoff: ${APP_CONFIG_RETRY_BACKOFF:1s}

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
    enabled: false
  swagger-ui:
    disable-swagger-default-url: true
    url: /openapi.yml
    path: docs

---

spring:
  config:
    activate:
      on-profile: heroku
  data:
    mongodb:
      uri: mongodb+srv://psiservti:IpODgJBz3qcV5nok@inventorydb.7junjst.mongodb.net/inventory_db?retryWrites=true&w=majority&appName=inventorydb

---

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/test?retryWrites=true