spring:
  profiles:
    active: dev
  application:
    name: 'inventario-api'

keycloak:
  realm: catchup-realm
  auth-server-url: http://localhost:8081/auth
  ssl-required: external
  resource: maestro-client
  credentials:
    secret: 2d462b07-b424-49f1-bef6-db8480adb85e
  use-resource-role-mappings: true
  bearer-only: true

app:
  keycloak:
    serverUrl: http://localhost:8081/auth
    realm: catchup-realm
    clientId: maestro-client
    secret: 2d462b07-b424-49f1-bef6-db8480adb85e
  config:
    inventory:
      default-id: ZXC8GH
    retry:
      max-attempts: ${APP_CONFIG_RETRY_MAX_ATTEMPTS:3}
      backoff: ${APP_CONFIG_RETRY_BACKOFF:1s}

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
    enabled: false
  swagger-ui:
    disable-swagger-default-url: true
    url: /openapi.yml
    path: docs

---

spring:
  config:
    activate:
      on-profile: heroku
  datasource:
    url: jdbc:postgresql://ec2-44-212-250-48.compute-1.amazonaws.com:5432/d1bo571k42qkl2
    username: qkdlrsuwbhbigz
    password: da1fb910033a2da360aee6365d7132a592844ec917c64f7429892e1620d0f320
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/inventario
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false