spring:
  profiles:
    active: heroku
  application:
    name: 'inventario-api'

app:
  config:
    inventory:
      default-id: ${APP_CONFIG_INVENTORY_DEFAULT_ID:ZXC8GH}
    retry:
      max-attempts: ${APP_CONFIG_RETRY_MAX_ATTEMPTS:3}
      backoff: ${APP_CONFIG_RETRY_BACKOFF:1s}

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
    enabled: false
  swagger-ui:
    disable-swagger-default-url: true
    url: /openapi.yml
    path: docs

---

spring:
  config:
    activate:
      on-profile: heroku
  data:
    mongodb:
      uri: ${MONGODB_URI}

---

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/test?retryWrites=true